source 'http://rubygems.org'

gem 'sinatra', '~> 1.1.2'
gem 'sinatra-mapping'
gem 'mongoid','2.0.0.rc.7'
gem 'mongoid_taggable'
gem 'bcrypt-ruby'
gem 'carrierwave'
gem 'bson_ext'
gem 'fog'
gem 'i18n'
gem 'uuidtools'
gem 'rmagick'
gem 'haml'
gem 'actionmailer', '~> 3.0.4'
gem 'rack-flash'
gem 'unicorn'

group :development do
  gem 'sinatra-reloader', :require => 'sinatra/reloader'
  gem 'awesome_print'
end

